adding project
josewweee/pokemonWeb pull request #1
Opened 2020-09-18 18:24 UTC by josewweee

adding the full project, i had to delete the last repo with all the commits due a mistake

2020-09-18 19:20 UTC, hackeo1 requested changes
- check the colors in css, they must be consistent (use the same unit) and try to use css variables
- don't use Spanish in your code
- don't use comments if the code can be explained by using variables/function/file names
- review your store as it is overloading the server with calls every time the page refreshes, you must use the listing to get the info for the list and the details only when they are required by the user

2020-09-18 19:20 UTC, hackeo1 commented on src/App.js
> +        <Banner/>
check the indentation in these tags

2020-09-18 19:20 UTC, hackeo1 commented on src/components/banner/Banner.js
> +}
use 2 space indentation

2020-09-18 19:20 UTC, hackeo1 commented on src/components/banner/banner.module.css
> +  background-position: center;
try using the shorthand for background

2020-09-18 19:20 UTC, hackeo1 commented on src/components/banner/banner.module.css
> +  color: white;
use variables for the css

2020-09-18 19:20 UTC, hackeo1 commented on src/components/navBar/NavBar.js
> +    let inputRef = React.createRef()
the name should be self explanatory, remove the comment

2020-09-18 19:20 UTC, hackeo1 commented on src/components/navBar/NavBar.js
> +    const [cancelButtonClass, setCancelButtonClass] = useState('query-button hidden')
the name should be self explanatory, remove the comment

2020-09-18 19:20 UTC, hackeo1 commented on src/components/navBar/NavBar.js
> +    const handleSearchBar = (e) => {
the name should be self explanatory, remove the comment.
don't use single character variables

2020-09-18 19:20 UTC, hackeo1 commented on src/components/navBar/NavBar.js
> +        if(e.target.value === '') {
if you have to explain with a comment, use another function and call it with a name that explains what you would have in the comment

2020-09-18 19:20 UTC, hackeo1 commented on src/components/navBar/NavBar.js
> +        setCancelButtonClass('query-button')
the name should be self explanatory, remove the comment

2020-09-18 19:20 UTC, hackeo1 commented on src/components/navBar/NavBar.js
> +    const cleanQuery = () => {
the name should be self explanatory, remove the comment

2020-09-18 19:20 UTC, hackeo1 commented on src/components/navBar/NavBar.js
> +                <h5 className='main'>PokéApp</h5>
I believe the use of the h5 is not correct as there is no header 3 or 4, don't use headers for styling, use them to paint a map of you app

2020-09-18 19:20 UTC, hackeo1 commented on src/components/navBar/styles.css
> +  /* width: 100%; */
remove comment

2020-09-18 19:20 UTC, hackeo1 commented on src/components/navBar/styles.css
> +  background-color: lightgray;
use variables

2020-09-18 19:20 UTC, hackeo1 commented on src/components/navBar/styles.css
> +  outline: #52b5de solid 2px;
use variables

2020-09-18 19:20 UTC, hackeo1 commented on src/components/overlay/UseOverlay.js
> +        else setOverlayState('hidden')
add the opening and closing brackets, omitting them leads to confusion

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> +/* GRAFICAS INDIVIDUALES */
Don't use Spanish

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> +    const stats = data.pokemonData.stats.map(stat => stat.base_stat);
remove comment, if it is required, use a function with a descriptive name

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> +    const comparedStats = data.comparedPokemon? data.comparedPokemon.stats.map(stat => stat.base_stat): null;
remove comment, if it is required, use a function with a descriptive name

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> +    let dataSet;
name should be self explanatory, remove comment

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> +                     {name: '', pokemonData: stats[4], comparedPokemon: comparedStats[4]}, {name: 'speed', pokemonData: stats[5], comparedPokemon: comparedStats[5]}];
move each object to its own line when defining arrays, if the object has many attributes, each attribute should be in its own line

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> +      {/* Si estamos comparando mostramos la segunda barra */}
remove comment, if it is required, use a function with a descriptive name

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> + const ModalHeaderPokemon = ({props}) => {
avoid having multiple components in the same file

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> +     const handleCloseModal = () => {
name should be self explanatory, remove comment

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> +            <h6 className='header-texts--name'>{data.pokemonData.name}</h6>
avoid using BEM unless the project requires to use it, it has very strict rules, and people in our teams don't use it

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> +            {/* HEADER */}
if you need to add comments, use a function with a descriptive name instead

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/style.css
> +  padding-right: 0 !important;
don't use important

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/style.css
> +  width: max-content !important;
don't use important, avoid using non unit values for sizes (they work different in different browsers)

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/style.css
> +  width: fit-content;
avoid using non unit values for sizes (they work different in different browsers)

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/style.css
> +/* MODAL */
use different files instead

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/style.css
> +.body-comparing--description li {
use classes instead of tags, tags can change any time

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon/Pokemon.js
> +            <img src={props.data.sprites.front_default} alt='imagen pokemon' className='card-img'></img>
img is self closing

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon/styles.css
> +  border: 1px solid rgb(181 175 175) !important;
don't use important

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemon-modal/style.css
> +  position: absolute !important;
don't use important

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemons-list/PokemonList.js
> +            props.fetch(i)
this looks like you are fetching one by one, is this the case?

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemons-list/PokemonList.js
> +    let limitIndex = id + 20
make the index into a variable/constant easy to change

2020-09-18 19:20 UTC, hackeo1 commented on src/components/pokemons-list/styles.css
> +    max-width: 792px !important;
don't

2020-09-18 19:20 UTC, hackeo1 commented on src/redux/actions/fetchActions.js
> +        fetch(`https://pokeapi.co/api/v2/pokemon/${id}`)
this fetches one by one, you must use the listing functionality, this is taking into account a sequential id approach, use the listing call to load the list and use this one only to get details

2020-09-18 19:20 UTC, hackeo1 commented on src/redux/actions/fetchActions.js
> +                let en_text = aditionalData.flavor_text_entries.find(item => item.language.name === 'en').flavor_text
name your variables in camel case

2020-09-18 19:20 UTC, hackeo1 commented on src/redux/actions/fetchActions.js
> +                    type: FETCH_POSTS_SUCCESS,
name your actions according to you app, you are not loading posts

2020-09-21 22:48 UTC, hackeo1 requested changes
- use single quotes for javascript
- the list and details must be load on demand, the details must be loaded only when the user request the details

2020-09-21 22:48 UTC, hackeo1 commented on .vscode/settings.json
> +}
don't upload IDE specific files

2020-09-21 22:48 UTC, hackeo1 commented on src/App.js
> +import UseOverlay from "./components/overlay";
use double quotes

2020-09-21 22:48 UTC, hackeo1 commented on src/App.js
> +function App() {
remove comment

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemon-modal/modal-body/ModalBody.js
> +export const ModalBodyComparing = ({ data }) => (
Put the components in different files

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemon-modal/modal-body/ModalBody.js
> +          </div>
this is very repetitive, use programatic values

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemon-modal/modal-body/style.css
> +/* TRICK: this replaces the width: max-content */
Remove the comment

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemon-modal/modal-body/style.css
> +  padding-right: 0 !important;
don't use importat

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemon-modal/modal-body/style.css
> +  padding-left: 0 !important;
don't use important

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemon-modal/modal-body/style.css
> +.body-comparing--description ul {
use classes instead

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemon-modal/modal-footer/style.css
> +  position: absolute !important;
don't use important

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemon-modal/modal-header/ModalHeader.js
> +  const handleCompare = () => {
remove the comment, use more descriptive names instead of using the comments

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemon-modal/modal-header/style.css
> +  background-color: rgb(92, 92, 92);
use variables, make them consistent

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemon-modal/style.css
> +/* MODAL */
remove the comment

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemons-list/PokemonList.js
> +  let id = props.pokemons.index;
remove the comments, make the names more descriptive

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemons-list/PokemonList.js
> +        {/* POKEMONS IF IN A QUERY */}
use functions instead of comments

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemons-list/styles.css
> +  box-shadow: 2px 1px 10px #0000008c;
use variables

2020-09-21 22:48 UTC, hackeo1 commented on src/components/pokemons-list/styles.css
> +    max-width: 1000px !important;
don't

2020-09-21 22:48 UTC, hackeo1 commented on src/redux/actions/fetchActions.js
> +      else pokemonReady.gender = "Male";
don't use single line ifs, specially if it has else if

2020-09-21 22:48 UTC, hackeo1 commented on src/redux/actions/fetchActions.js
> +    jsonPokemonsPageList.results.forEach(async (result) => {
this should be done when the user clicks the details, don't load data when the user has not requested it

2020-09-22 13:18 UTC, josewweee commented on src/App.js
> +import UseOverlay from "./components/overlay";
single quotes you mean?

2020-09-22 14:35 UTC, josewweee commented on src/components/pokemon-modal/modal-footer/style.css
> +  position: absolute !important;
this one is necessary to overwrite the graph library default inline style

2020-09-22 16:58 UTC, hackeo1 requested changes

2020-09-22 16:58 UTC, hackeo1 commented on src/colors.css
> +  --hover-black: rgb(92, 92, 92);
use hex

2020-09-22 16:58 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> +// import { ModalBodyPokemon, ModalBodyComparing } from './modal-body/ModalBody';
remove comment

2020-09-22 16:58 UTC, hackeo1 commented on src/components/pokemons-list/styles.css
> +  transition: all 2s linear;
use only the attributes that change

2020-09-22 16:58 UTC, hackeo1 commented on src/redux/actions/fetchActions.js
> +export const increasePokemonId = () => {
remove comment, this should be explained using constants/variables in the reducer

2020-09-22 16:58 UTC, hackeo1 commented on src/redux/actions/fetchActions.js
> +export const queryPokemons = (query) => {
remove comment

2020-09-22 16:58 UTC, hackeo1 commented on src/redux/actions/fetchActions.js
> +export const cancelQuery = () => {
remove comment

2020-09-22 16:58 UTC, hackeo1 commented on src/redux/reducers/index.js
> +/* MIXING THE REDUCERS INTO ONE */
remove

2020-09-22 16:58 UTC, hackeo1 commented on src/redux/reducers/modalReducer.js
> +/* OPEN AND CLOSE THE MODAL, SENDING POKEMON DATA DEPENDING OF WHICH ONE WAS SELECTED */
remove

2020-09-22 16:58 UTC, hackeo1 commented on src/redux/reducers/pokemonsReducer.js
> +/* FETCH POKEMONS TO THE API */
remove

2020-09-22 16:58 UTC, hackeo1 commented on src/redux/store.js
> +/* CREATING THE REDUX STORE TO BE USED BY THE COMPONENTS */
remove

2020-09-22 18:36 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> +    }, 100);
avoid using timeouts

2020-09-22 18:36 UTC, hackeo1 commented on src/components/pokemon-modal/PokemonModal.js
> +      <div className="root-modal" style={!modalOpacity ? { opacity: 1 } : { opacity: 0 }}>
add or remove a class and use css animations for the delay

2020-09-22 19:16 UTC, hackeo1 approved these changes

2021-03-05 13:04 UTC, merged